name: Lighthouse CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  lighthouse:
    name: Lighthouse Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.11.x

      - name: Run Lighthouse CI
        run: |
          npx lhci autorun || echo "Lighthouse CI failed"

      - name: Upload report
        uses: actions/upload-artifact@v3.1.3
        with:
          name: lighthouse-report
          path: .lighthouseci
