name: Lighthouse Audit

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Run Lighthouse CI
        run: |
          lhci autorun --collect.url=https://promelektroservice.vercel.app \
                       --upload.target=filesystem \
                       --upload.outputDir=./lhci-report

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-report
          path: lhci-report
